package haxe.imp.parser.antlr.tree;

public enum TreeTokens {
	PROPERTY_DECL, MODULE, SUFFIX_EXPR, BLOCK_SCOPE, PARAM_LIST, TYPE_TAG, TYPE_PARAM_OPT, INHERIT_LIST_OPT, DECL_ATTR_LIST, VAR_INIT, PACKAGE;
}
